build(deps): update ramenctl to v0.9.0
This version include many improvements and fixes since v0.8.0:
https://github.com/RamenDR/ramenctl/releases/tag/v0.9.0

Generated using:

    % go get github.com/ramendr/ramenctl@v0.9.0
    go: downloading github.com/ramendr/ramenctl v0.9.0
    go: upgraded github.com/distribution/reference v0.5.0 => v0.6.0
    go: upgraded github.com/nirs/kubectl-gather v0.8.0 => v0.9.0
    go: upgraded github.com/prometheus/client_golang v1.21.1 => v1.22.0
    go: upgraded github.com/ramendr/ramen/api v0.0.0-20250313143647-8dd671566929 => v0.0.0-20250710152106-9a4f493138c5
    go: upgraded github.com/ramendr/ramen/e2e v0.0.0-20250702155156-54e270d8dc49 => v0.0.0-20250722150952-d4c9b950df94
    go: upgraded github.com/ramendr/ramenctl v0.8.0 => v0.9.0
    go: upgraded golang.org/x/exp v0.0.0-20250305212735-054e65f0b394 => v0.0.0-20250711185948-6ae5c78190dc
    go: upgraded k8s.io/apiextensions-apiserver v0.32.4 => v0.33.0
    go: upgraded k8s.io/cli-runtime v0.32.3 => v0.33.2
    go: upgraded k8s.io/component-base v0.32.4 => v0.33.2
    go: upgraded k8s.io/kubectl v0.31.1 => v0.33.2
    go: upgraded sigs.k8s.io/controller-runtime v0.20.4 => v0.21.0

And replacing github.com/docker/distribution/reference with v2.8.2 to avoid this build error:

    % make
    ...
    env GOOS=darwin GOARCH=arm64 go build -o bin/odf  cmd/odf/main.go
    # github.com/docker/distribution/reference
    ../../go/pkg/mod/github.com/docker/distribution@v2.8.3+incompatible/reference/reference_deprecated.go:122:19: undefined: reference.SplitHostname

Signed-off-by: Nir Soffer <nsoffer@redhat.com>